on:
  push:
jobs:
  trigger-workflow-from-other-repo:
    runs-on: ubuntu-latest
    steps:
      - name: trigger another workflow from node-hello repo
        run: |
            curl -X POST https://api.github.com/repos/meditator3/node-hello/actions/workflows/trigger-by-parameter.yml/dispatches \
            -H 'Accept: application/vnd.github.v3+json' \
            --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --data '{"ref": "${{ github.ref }}"}'
  
