on:
  push:
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: trigger another workflow git-action-demo
        run: |
            curl -X POST https://api.github.com/repos/meditator3/node-hello/actions/workflows/trigger-by-parameter.yml/dispatches
            -H 'Accept: application/vnd.github.v3+json' \
            --header 'Authorization: Bearer ${{ secrets.REPO_ACCESS_TOKEN }}' \
            --data '{"ref": "${{ github.ref }}"}'
  
